locals {
  common_tags = {
    Project = "finalexam-sqa114"
  }
}

data "aws_ami" "amazon_linux_x86" {
  most_recent = true
  owners      = ["amazon"]

  filter {
    name   = "name"
    values = ["al2023-ami-*-x86_64"]
  }

  filter {
    name   = "architecture"
    values = ["x86_64"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }

  filter {
    name   = "root-device-type"
    values = ["ebs"]
  }
}

# To create the Jenkins Controller
resource "aws_instance" "jenkins_controller" {
  ami                         = data.aws_ami.amazon_linux_x86.id
  instance_type               = var.instance_type
  subnet_id                   = aws_subnet.main_a.id
  vpc_security_group_ids      = [aws_security_group.web_sg.id]
  key_name                    = aws_key_pair.this.key_name
  associate_public_ip_address = true
  user_data                   = file("${path.module}/scripts/jenkins_install.sh")

  # To copy the same key that was generated by Terraform
  provisioner "file" {
    content     = tls_private_key.this.private_key_pem
    destination = "/home/ec2-user/.ssh/finalexam.pem"
  }

  provisioner "remote-exec" {
    inline = [
      "chmod 600 /home/ec2-user/.ssh/finalexam.pem",
      "chown ec2-user:ec2-user /home/ec2-user/.ssh/finalexam.pem"
    ]
  }

  connection {
    type        = "ssh"
    host        = self.public_ip
    user        = "ec2-user"
    private_key = tls_private_key.this.private_key_pem
  }

  tags = merge(local.common_tags, { Name = "JenkinsController" })
}

# To create the Jenkins Agent (permanent) -> This one will use the pipeline
resource "aws_instance" "jenkins_agent_permanent" {
  ami                         = data.aws_ami.amazon_linux_x86.id
  instance_type               = var.instance_type
  subnet_id                   = aws_subnet.main_a.id
  vpc_security_group_ids      = [aws_security_group.web_sg.id]
  key_name                    = aws_key_pair.this.key_name
  associate_public_ip_address = true
  user_data                   = file("${path.module}/scripts/agent_install.sh")

  # To copy the private key to the permanent agent
  provisioner "file" {
    content     = tls_private_key.this.private_key_pem
    destination = "/home/ec2-user/.ssh/finalexam.pem"
  }

  provisioner "remote-exec" {
    inline = [
      "chmod 600 /home/ec2-user/.ssh/finalexam.pem",
      "chown ec2-user:ec2-user /home/ec2-user/.ssh/finalexam.pem"
    ]
  }

  connection {
    type        = "ssh"
    host        = self.public_ip
    user        = "ec2-user"
    private_key = tls_private_key.this.private_key_pem
  }

  tags = merge(local.common_tags, { Name = "JenkinsAgentPermanent" })
}

# To create the Jenkins Agent (dynamic)
resource "aws_instance" "jenkins_agent_dynamic" {
  ami                         = data.aws_ami.amazon_linux_x86.id
  instance_type               = var.instance_type
  subnet_id                   = aws_subnet.main_b.id
  vpc_security_group_ids      = [aws_security_group.web_sg.id]
  key_name                    = aws_key_pair.this.key_name
  associate_public_ip_address = true
  user_data                   = file("${path.module}/scripts/agent_install.sh")

  tags = merge(local.common_tags, { Name = "JenkinsAgentDynamic" })
}

# To create the Testing
resource "aws_instance" "testing" {
  ami                         = data.aws_ami.amazon_linux_x86.id
  instance_type               = var.instance_type
  subnet_id                   = aws_subnet.main_a.id
  vpc_security_group_ids      = [aws_security_group.web_sg.id]
  key_name                    = aws_key_pair.this.key_name
  associate_public_ip_address = true
  user_data                   = file("${path.module}/scripts/web_install.sh")

  tags = merge(local.common_tags, { Name = "Testing" })
}

# To create the Staging
resource "aws_instance" "staging" {
  ami                         = data.aws_ami.amazon_linux_x86.id
  instance_type               = var.instance_type
  subnet_id                   = aws_subnet.main_b.id
  vpc_security_group_ids      = [aws_security_group.web_sg.id]
  key_name                    = aws_key_pair.this.key_name
  associate_public_ip_address = true
  user_data                   = file("${path.module}/scripts/web_install.sh")

  tags = merge(local.common_tags, { Name = "Staging" })
}

# To create the Prod_Env1
resource "aws_instance" "prod_env1" {
  ami                         = data.aws_ami.amazon_linux_x86.id
  instance_type               = var.instance_type
  subnet_id                   = aws_subnet.main_a.id
  vpc_security_group_ids      = [aws_security_group.web_sg.id]
  key_name                    = aws_key_pair.this.key_name
  associate_public_ip_address = true
  user_data                   = file("${path.module}/scripts/web_install.sh")

  tags = merge(local.common_tags, { Name = "Production_Env1" })
}

# To create the Prod_Env2
resource "aws_instance" "prod_env2" {
  ami                         = data.aws_ami.amazon_linux_x86.id
  instance_type               = var.instance_type
  subnet_id                   = aws_subnet.main_b.id
  vpc_security_group_ids      = [aws_security_group.web_sg.id]
  key_name                    = aws_key_pair.this.key_name
  associate_public_ip_address = true
  user_data                   = file("${path.module}/scripts/web_install.sh")

  tags = merge(local.common_tags, { Name = "Production_Env2" })
}
